# Aliases
alias:
  # OpenRouter
  - "sonnet:openrouter/anthropic/claude-sonnet-4"
  - "deepseek-chat:openrouter/deepseek/deepseek-chat-v3-0324"
  - "gemini-pro:openrouter/google/gemini-2.5-pro-preview"
  - "gemini-flash:openrouter/google/gemini-2.5-flash-preview-05-20"
  - "gemma:openrouter/google/gemma-3n-e4b-it:free"

  # GitHub Copilot
  - "sonnet-3.5:openai/claude-3.5-sonnet"
  - "sonnet-3.7:openai/claude-3.7-sonnet"
  - "sonnet-4:openai/claude-sonnet-4"
  - "gemini-pro-2.5:openai/gemini-2.5-pro"
  - "gpt-4.1:openai/gpt-4.1"
  - "o4-mini:openai/o4-mini"

  # Ollama
  - "gemma-local:ollama_chat/gemma3:4b"

  # labels:
  - "power:openai/gemini-2.5-pro"
  - "econo:openai/gpt-4.1"

# Models
model: gpt-4.1
editor-model: power
weak-model: econo

openai-api-base: https://api.githubcopilot.com

# edit-format: whole # options; diff, whole, udiff, diff-fenced
architect: false

# Theme: Black Metal
# Main text colors
user-input-color: "#f8f8f2" # "#ff79c6"
assistant-output-color: "#f8f8f2"
tool-output-color: "#608787"
tool-error-color: "#ff5555"
tool-warning-color: "#CBC983"

# Completion menu colors (terminal-based)
completion-menu-color: "#f8f8f2"
completion-menu-bg-color: "#282a36"
completion-menu-current-color: "#f8f8f2"
completion-menu-current-bg-color: "#44475a"

# Code theme for markdown syntax highlighting
code-theme: "coffee"

# Editor Configuration
editor: nvim

# Streaming
stream: true
show-model-warnings: false

# Git Settings
auto-commits: false
no-attribute-author: true
no-attribute-committer: true
show-diffs: false  # Optional, but useful to review changes

# Input Mode
suggest-shell-commands: false
vim: true
multiline: false  # Often useful with vim mode
restore-chat-history: false  # Helps maintain context between sessions

# Disable automatic linting/testing as requested
auto-lint: false
auto-test: false

# Cache Settings
cache-prompts: true
cache-keepalive-pings: 12

check-update: false
