# Model settings for the Aider models
# Note: use_temperature, streaming, and use_system_prompt set to false for reasoning models

- name: openai/gemini-2.5-pro
  edit_format: diff
  weak_model_name: openai/claude-3.5-sonnet
  use_repo_map: true
  use_temperature: false
  editor_model_name: openai/gemini-2.5-pro
  editor_edit_format: editor_diff
  # max_tokens:
  # max_input_tokens:
  # max_output_tokens:
