# Aider Configuration File
# Github Copilot: openai completion endpoint
openai-api-base: https://api.githubcopilot.com
# Models
model: openai/gemini-2.5-pro
editor-model: openai/claude-sonnet-4.5
weak-model: openai/gpt-4o

# edit-format: whole # options; diff, whole, udiff, diff-fenced
architect: false

# Theme: Black Metal
# Main text colors
user-input-color: "#f8f8f2"
assistant-output-color: "#f8f8f2"
tool-output-color: "#f8f8f2"
tool-error-color: "#ff5555"
tool-warning-color: "#f8f8f2"

# Completion menu colors (terminal-based)
completion-menu-color: "#f8f8f2"
completion-menu-bg-color: "#282a36"
completion-menu-current-color: "#f8f8f2"
completion-menu-current-bg-color: "#44475a"

# Code theme for markdown syntax highlighting
code-theme: "monokai"

# Editor Configuration
editor: nvim

# Streaming
stream: true
show-model-warnings: false

# Git Settings
auto-commits: false
no-attribute-author: true
no-attribute-committer: true
show-diffs: false # Optional, but useful to review changes

# Input Mode
suggest-shell-commands: false
vim: true
multiline: false # Often useful with vim mode
restore-chat-history: false # Helps maintain context between sessions

# Disable automatic linting/testing as requested
auto-lint: false
auto-test: false

# Cache Settings
cache-prompts: true
cache-keepalive-pings: 12

check-update: false
