# ~/.tmux.conf
# Tmux configuration file
#
# General -----------------------------------------
# Set the prefix
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# Mouse support
set -g mouse on

# Base index for windows and panes (start from 1)
set -g base-index 1
set -g pane-base-index 1

# Copy-mode mods
set -g history-limit 100000 # Increase scrollback buffer

# Window management --------------------------------
# View
bind r move-window -r # renumber
set -g set-title on
set -g set-titles-string "#T"
bind i command-prompt "rename-window %%" # rename

# Create
bind C new-window -c "#{pane_current_path}" # new window cwd

# Move
bind Tab next-window
bind Tab previous-window

# Remove
bind q kill-window

# Pane management ---------------------------------
# Split
bind h split-window -h -b -t:+1 -c "#{pane_current_path}"
bind j split-window -v -c "#{pane_current_path}"
bind k split-window -v -b -t:+1 -c "#{pane_current_path}"
bind l split-window -h -c "#{pane_current_path}"

# Resize
bind-key -n M-k resize-pane -U 5
bind-key -n M-j resize-pane -D 5

# Misc ---------------------------------------------

# Images (in Neovim)
set -gq allow-passthrough on
set -g visual-activity off

# Configuration
bind R source-file ~/.tmux.conf \; display-message "tmux config reloaded"

