# ~/.tmux.conf
# Tmux configuration file
#
# General -----------------------------------------
# Set the prefix
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# Mouse support
set -g mouse on

# Base index for windows and panes (start from 1)
set -g base-index 1
set -g pane-base-index 1

# Copy-mode mods
set -g history-limit 100000 # Increase scrollback buffer

setw -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind-key -T copy-mode-vi Escape send-keys -X cancel
bind P paste-buffer

# Server management ---------------------------------
bind S new-session
set -s focus-events on
set -s extended-keys on
set -s escape-time 0

# Window management --------------------------------
# View
bind r move-window -r # renumber

# Create
bind W new-window -c "#{pane_current_path}" # new window cwd

# Move
bind Tab next-window

bind-key 1 select-window -t :1
bind-key 2 select-window -t :2
bind-key 3 select-window -t :3
bind-key 4 select-window -t :4
bind-key 5 select-window -t :5

# Remove
bind q kill-window

# Pane management ---------------------------------
# Split
bind h split-window -h -b -t:+0 -c "#{pane_current_path}"
bind j split-window -v -c "#{pane_current_path}"
bind k split-window -v -b -t:+0 -c "#{pane_current_path}"
bind l split-window -h -c "#{pane_current_path}"

# Move
bind C-h select-pane -L
bind C-j select-pane -D
bind C-k select-pane -U
bind C-l select-pane -R

bind-key -r Tab select-pane -t :.+  # Cycle to next pane

# Resize
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Misc ---------------------------------------------
# Rename session
bind I command-prompt -p "rename-session:" "rename-session '%%'"
# Rename window
bind i command-prompt -p "rename window:" "rename-window %%"

# Images (in Neovim)
set -gq allow-passthrough on
set -g visual-activity off

# Configuration
bind R source-file ~/.tmux.conf \; display-message "tmux config reloaded"
