# Kitty theme port of Autumn

foreground                      #F3F2CC
background                      #161616
selection_foreground            #faf4c6
selection_background            #525252
cursor                          #626262
cursor_text_color               #F3F2CC

# Black
color0                          #292929
color8                          #6B6B6B

# Red
color1                          #EB5D49
color9                          #EB5D49

# Green
color2                          #92AF72
color10                         #92AF72

# Yellow
color3                          #E8A75C
color11                         #E8A75C

# Blue
color4                          #7895B7
color12                         #7895B7

# Magenta
color5                          #CBC983
color13                         #CBC983

# Cyan
color6                          #B3EBBF
color14                         #B3EBBF

# White
color7                          #F3F2CC
color15                         #f6f3e8

active_tab_foreground           #292929
active_tab_background           #6c6c6c
inactive_tab_foreground         #6c6c6c
inactive_tab_background         #292929
tab_bar_background              #292929
