# ~/.config/kitty/kitty.conf
#
# System and Remote Control ----------------------------
## Remote Access
allow_remote_control yes
listen_on unix:/tmp/nicekitty
macos_quit_when_last_window_closed yes

# Font Configuration ------------------------------------
## Primary Font Settings
font_family      family="JetBrainsMono Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 16

## Advanced Font Rendering
modify_font cell_width 100%
modify_font cell_height 1px

# Text Rendering -----------------------------------------
## Drawing and Composition
box_drawing_scale 0.001, 0.85, 1, 1.5
text_composition_strategy 1.0 15

# Performance Tuning -------------------------------------
input_delay 2
sync_to_monitor no

# Visual Appearance --------------------------------------
## Theme (see below)
# include themes/OneDark.conf

## Transparency and Opacity
background_opacity 1.0

## Cursor Styling
# cursor red
cursor_shape block
cursor_blink_interval -1
cursor_trail 6

## Color and Border Settings
# active_border_color #9D221F
inactive_text_alpha .55

# User Experience ----------------------------------------
## Interaction Preferences
mouse_hide_wait 3.0
copy_on_select clipboard

## Feedback Mechanisms
enable_audio_bell yes
visual_bell_duration 0.25

# Window Management --------------------------------------
## Window Layout
initial_window_width 800
initial_window_height 1000
draw_minimal_borders yes
window_padding_width 2 2 0 2
placement_strategy center
hide_window_decorations titlebar-only
macos_show_window_title_in none

# Tab Management -----------------------------------------
## Tab Bar Configuration
tab_bar_edge top
tab_bar_style powerline
tab_bar_align left
tab_bar_min_tabs 1
tab_separator " | "
tab_powerline_style round
active_tab_font_style bold
inactive_tab_font_style bold
tab_title_template "{fmt.fg.tab}{title}"
tab_title_max_length 0

# System Notifications -----------------------------------
notify_on_cmd_finish unfocused 10.0 notify

# Key Mappings ------------------------------------------

## Clipboard Operations
map cmd+c copy_to_clipboard
map cmd+v paste_from_clipboard

## Text Insertion Shortcuts
map alt+- send_text all \u0020<-\u0020
map alt+m send_text all \u0020|>\u0020

## Application Launches
map kitty_mod+v launch --cwd=current nvim
map kitty_mod+d launch --cwd=current ncdu
map kitty_mod+y launch --cwd=current yazi
map kitty_mod+r launch --cwd=current radian

## Window Management

## Layouts
enabled_layouts horizontal, stack, tall:bias=65

## Choose Layout
map kitty_mod+m toggle_layout stack
map kitty_mod+t toggle_layout tall
map kitty_mod+w toggle_layout horizontal
map kitty_mod+o next_layout

## Splits
map kitty_mod+l launch --cwd=current --location=split
map kitty_mod+j launch --cwd=current --location=hsplit

## Window Navigation
map kitty_mod+n next_window
map kitty_mod+p previous_window

map alt+1 first_window
map alt+2 second_window
map alt+3 third_window
map alt+4 fourth_window

## Window Movement
map kitty_mod+s swap_with_window

## Window Resizing
map alt+h resize_window wider 5
map alt+k resize_window shorter 5
map alt+j resize_window taller 5
map alt+l resize_window narrower 5

## Tab Management
map ctrl+tab next_tab
map cmd+1 goto_tab 1
map cmd+2 goto_tab 2
map cmd+3 goto_tab 3
map cmd+4 goto_tab 4
map cmd+5 goto_tab 5
map cmd+6 goto_tab 6
map cmd+7 goto_tab 7
map cmd+8 goto_tab 8
map cmd+9 goto_tab 9
map kitty_mod+i set_tab_title
map kitty_mod+q discard_event

## Configuration
map cmd+, edit_config_file
map ctrl+cmd+, load_config_file

# BEGIN_KITTY_THEME
# Gruvbox Dark Hard
include current-theme.conf
# END_KITTY_THEME
