# ~/.config/kitty/kitty.conf
#
# System and Remote Control ----------------------------
## Remote Access
allow_remote_control yes
listen_on unix:/tmp/nicekitty
macos_quit_when_last_window_closed yes

# Font Configuration ------------------------------------
## Primary Font Settings
font_family family="Hack Nerd Font"
font_size 14
disable_ligatures never

## Advanced Font Rendering
modify_font cell_width 100%
modify_font cell_height 1px

# Text Rendering -----------------------------------------
## Drawing and Composition
box_drawing_scale 0.001, 0.85, 1, 1.5
text_composition_strategy 1.0 15
sync_to_monitor no

# Visual Appearance --------------------------------------
## Theme
include themes/Gruvbox-Dark-Hard.conf

## Transparency and Opacity
background_opacity 1.0

## Cursor Styling
cursor red
cursor_shape block
cursor_blink_interval -1
cursor_trail 3

## Color and Border Settings
active_border_color #eeeeee
inactive_text_alpha .75

# User Experience ----------------------------------------
## Interaction Preferences
mouse_hide_wait 3.0
copy_on_select clipboard

## Feedback Mechanisms
enable_audio_bell no
visual_bell_duration 0.25

# Window Management --------------------------------------
## Window Layout
initial_window_width 800
initial_window_height 1000
draw_minimal_borders yes
window_padding_width 2 2 0 2
placement_strategy center
hide_window_decorations titlebar-only

## Layouts
enabled_layouts fat, grid, horizontal, splits, vertical, stack

# Tab Management -----------------------------------------
## Tab Bar Configuration
tab_bar_edge top
tab_bar_style powerline
tab_bar_align left
tab_bar_min_tabs 1
tab_separator " | "
tab_powerline_style round
active_tab_font_style bold
inactive_tab_font_style bold
tab_title_template "{fmt.fg.tab}{title}"

# System Notifications -----------------------------------
notify_on_cmd_finish unfocused 10.0 notify

# Key Mappings ------------------------------------------

## Clipboard Operations
map cmd+c copy_to_clipboard
map cmd+v paste_from_clipboard

## Text Insertion Shortcuts
map alt+- send_text all \u0020<-\u0020
map alt+m send_text all \u0020|>\u0020

## Application Launches
map kitty_mod+v launch --cwd=current nvim
map kitty_mod+d launch --cwd=current ncdu
map kitty_mod+y launch --cwd=current yazi
map kitty_mod+r launch --cwd=current radian

## Window Management
map kitty_mod+enter new_window_with_cwd
map ctrl+alt+enter new_window
map kitty_mod+n next_window
map kitty_mod+p previous_window
map kitty_mod+` move_window_to_top
map kitty_mod+0 move_window_forward
map kitty_mod+1 move_window_backward
map kitty_mod+r start_resizing_window
map kitty_mod+s swap_with_window

## Window Navigation
map alt+1 first_window
map alt+2 second_window
map alt+3 third_window
map alt+4 fourth_window

## Window Resizing
map kitty_mod+h resize_window narrower 5
map kitty_mod+j resize_window taller 5
map kitty_mod+k resize_window shorter 5
map kitty_mod+l resize_window wider 5

## Tab Management
map ctrl+tab next_tab
map kitty_mod+i set_tab_title
map cmd+1 goto_tab 1
map cmd+2 goto_tab 2
map cmd+3 goto_tab 3
map cmd+4 goto_tab 4
map cmd+5 goto_tab 5
map cmd+6 goto_tab 6
map cmd+7 goto_tab 7
map cmd+8 goto_tab 8
map cmd+9 goto_tab 9

## Layout Control
map kitty_mod+p next_layout
map kitty_mod+m toggle_layout stack

## Configuration
map cmd+, edit_config_file
map ctrl+cmd+, load_config_file

