{
  hostname,
  lib,
  ...
}: let
  keyPaths = import ./ssh-key-paths.nix {inherit hostname;};
  # Use FQDN: macOS does not apply Tailscale's supplemental search domain
  # consistently to unqualified names.
  tailnet = "gerbil-matrix.ts.net";

  plainHosts = [
    {
      host = "services";
      name = "core-services";
      user = "root";
    }
    {
      host = "media";
      name = "media-services";
      user = "root";
    }
    {
      host = "homeassistant";
      name = "homeassistant";
      user = "jeridf";
    }
    {
      host = "proxmox";
      name = "minis-proxmox";
      user = "root";
    }
  ];
in {
  # Airborne's ~/.config resolves into dotfiles; managing this target could
  # back up and replace the canonical registry. Other hosts need filesystem
  # review before activation. Registry contains public metadata only.
  xdg.configFile."ssh/keys.yaml" = {
    enable = hostname != "Macbook-Airborne";
    source = ../../ssh/keys.yaml;
    force = false;
  };

  home.sessionVariables = lib.optionalAttrs (keyPaths.nickname != null) {
    SSH_KEY_AUDIT_DEVICE = keyPaths.nickname;
  };

  home.file.".ssh/config.d/nix-managed.conf".text =
    ''
      # Generated by Home Manager. Do not edit directly.
      # Generate local device/service keys and register public keys before activation.
    ''
    + lib.optionalString (keyPaths.nickname != null) ''
        # Match alias and literal FQDN for existing Git remotes.
        Host forgejo forgejo.${tailnet}
          HostName forgejo.${tailnet}
          HostKeyAlias forgejo
          User forgejo
          IdentityFile ${keyPaths.services.forgejo}
          IdentitiesOnly yes

        Host codeberg.org
          User git
          IdentityFile ${keyPaths.services.codeberg}
          IdentitiesOnly yes

        Host github.com
          User git
          IdentityFile ${keyPaths.services.github}
          IdentitiesOnly yes

      # --- tailnet boxes (generated) ---
      ${builtins.concatStringsSep "\n" (map plainHosts)}
    '';
}
