{
  home.file.".ssh/config.d/nix-managed.conf".text = ''
    # Generated by Home Manager. Do not edit directly.

    Host forgejo
      HostName forgejo
      User forgejo
      IdentityFile ~/.ssh/id_ed25519_forgejo
      IdentitiesOnly yes

    Host forgejo.gerbil-matrix.ts.net
      User forgejo
      IdentityFile ~/.ssh/id_ed25519_forgejo
      IdentitiesOnly yes

    Host codeberg.org
      User git
      IdentityFile ~/.ssh/id_ed25519_codeberg
      IdentitiesOnly yes

    Host rover
      HostName mini-rover
      User jeridf
      Port 22

    Host minicore
      HostName mac-minicore
      User jeridf
      Port 22
      IdentityFile ~/.ssh/id_ed25519_workstation
      IdentitiesOnly yes

    Host airborne
      HostName macbook-airborne
      User francojc
      Port 22
      IdentityFile ~/.ssh/id_ed25519_workstation
      IdentitiesOnly yes
  '';
}
