{
  hostname,
  lib,
  ...
}: let
  keyPaths = import ./ssh-key-paths.nix {inherit hostname;};
  # Use FQDN: macOS does not apply Tailscale's supplemental search domain consistently to unqualified names.
  tailnet = "gerbil-matrix.ts.net";

  plainHosts = [
    {
      host = "minicore";
      name = "mac-minicore";
      user = "jeridf";
    }
    {
      host = "airborne";
      name = "macbook-airborne";
      user = "francojc";
    }
    {
      host = "rover";
      name = "mini-rover";
      user = "jeridf";
    }
    {
      host = "services";
      name = "core-services";
      user = "root";
    }
    {
      host = "media";
      name = "media-services";
      user = "root";
    }
    {
      host = "homeassistant";
      name = "homeassistant";
      user = "jeridf";
    }
    {
      host = "proxmox";
      name = "minis-proxmox";
      user = "root";
    }
  ];
in {
  home.file.".ssh/config.d/nix-managed.conf".text =
    ''
      # Generated by Home Manager. Do not edit directly.
      # Generate local device/service keys and register public keys before activation.
    ''
    + lib.optionalString (keyPaths.nickname != null) ''
      # Match alias and literal FQDN for existing Git remotes.
      Host forgejo forgejo.${tailnet}
        HostName forgejo.${tailnet}
        HostKeyAlias forgejo
        User forgejo
        IdentityFile ${keyPaths.services.forgejo}
        IdentitiesOnly yes

      Host codeberg.org
        User git
        IdentityFile ${keyPaths.services.codeberg}
        IdentitiesOnly yes

      Host github.com
        User git
        IdentityFile ${keyPaths.services.github}
        IdentitiesOnly yes

    ''
    + lib.concatMapStringsSep "\n" (entry: ''
      Host ${entry.host}
        HostName ${entry.name}.${tailnet}
        User ${entry.user}
    '')
    plainHosts;
}
