#!/usr/bin/env bash

# This script fetches the student's remote repository, creates a new branch, and checks out the new branch. It takes the clone URL as an argument. This argument is then used to clone the student's remote repository. In addition, the URL argument is parsed and the student's GitHub username is extracted and the name of the new branch is set to the student's username.
# The script assumes that the current working directory is the relevant local repository.
# Example: ./fetch-student-remote.sh https://github.com/username/repo.git

# Add the clone URL as an argument
clone_url=$1

# Parse the clone URL to extract the student's GitHub username
student_username=$(echo $clone_url | cut -d'/' -f4)

# Add the clone URL to the remotes list, remote name is set to 'username'
git remote add $student_username $clone_url

# Fetch the student's remote repository from 'main'
git fetch $student_username main:$student_username

# Switch to the new branch
git checkout $student_username




