#!/usr/bin/env bash

# Get the mac address of the host computer
# Written by Shreyas Siravara

HOST="$1"
ARGS=$#

#Print usage message
if [ $ARGS -lt 1 ]
then
	echo -e "\nUsage: macfind [IPADDR]\n" > /dev/stderr
	exit 1
fi

ping -c 50 $HOST

#Find the host's mac address in your arp cache
arp -a
echo
