#!/usr/bin/env bash

# This script monitors changes in the current directory and previews the
# Quarto project when a change is detected. The script uses `ag` to monitor
# changes in the current directory and its subdirectories and the `entr` tool
# to run the `quarto preview` command when a change is detected. It also takes one
# argument, which is either 'html' or 'pdf' to specify the output format.
# Example usage:
# $ ./preview_watch.sh html

# Check if the argument is provided
if [ -z "$1" ]; then
    echo "Please provide the output format as an argument. It should be either 'html' or 'pdf'."
    exit 1
fi

# Check if the argument is either 'html' or 'pdf'

if [ "$1" != "html" ] && [ "$1" != "pdf" ]; then
    echo "The output format should be either 'html' or 'pdf'."
    exit 1
fi

# Check if the required tools are installed
if ! command -v ag &> /dev/null; then
    echo "The 'ag' tool is not installed. Please install it using 'brew install ag'."
    exit 1
fi

if ! command -v entr &> /dev/null; then
    echo "The 'entr' tool is not installed. Please install it using 'brew install entr'."
    exit 1
fi

# Run the `quarto render` command when a change is detected
ag -g '\.(qmd|tex|bib|cls|yml)$' | entr quarto preview --to $1

