#!/usr/bin/env python

import requests
import os

icon_mapping = {
    "01d": "☀️",
    "01n": "☾",
    "02d": "⛅︎",
    "02n": "⛅︎",
    "03d": "☁️",
    "03n": "☁️",
    "04d": "☁️",
    "04n": "☁️",
    "09d": "🌧️",
    "09n": "🌧️",
    "10d": "🌦️",
    "10n": "🌦️",
    "11d": "⛈️",
    "11n": "⛈️",
    "13d": "❄️",
    "13n": "❄️",
    "50d": "🌫️",
    "50n": "🌫️",
}

# Load API key from environment variable
api_key = os.getenv("OPENWEATHER_API_KEY")


def get_weather(location):
    api_key = api_key  # OpenWeatherMap API
    base_url = "https://api.openweathermap.org/data/2.5/weather"
    exclude = "minutely,hourly,daily,alerts"
    units = "imperial"  # use "metric" for Celsius
    complete_url = f"{base_url}?q={location}&exclude={exclude}&units={units}&appid={api_key}"
    response = requests.get(complete_url)
    if response.status_code == 200:
        data = response.json()
        current_temperature = round(data["main"]["temp"])
        icon_code = data["weather"][0]["icon"]
        icon_emoji = icon_mapping.get(icon_code, "❓")

        return f"{icon_emoji} {current_temperature}°F"

    else:
        return "Error fetching weather data"

print(get_weather("Winston-Salem, us"))
