#!/usr/bin/env python

import argparse
import requests
import os

icon_mapping = {
    "01d": "☀️",
    "01n": "☾",
    "02d": "⛅︎",
    "02n": "⛅︎",
    "03d": "☁️",
    "03n": "☁️",
    "04d": "☁️",
    "04n": "☁️",
    "09d": "🌧️",
    "09n": "🌧️",
    "10d": "🌦️",
    "10n": "🌦️",
    "11d": "⛈️",
    "11n": "⛈️",
    "13d": "❄️",
    "13n": "❄️",
    "50d": "🌫️",
    "50n": "🌫️",
}


def get_weather(location):
    api_key = os.getenv("OPENWEATHER_API_KEY")  # OpenWeatherMap API
    base_url = "https://api.openweathermap.org/data/2.5/weather"
    exclude = "minutely,hourly,daily,alerts"
    units = "imperial"  # use "metric" for Celsius
    complete_url = (
        f"{base_url}?q={location}&exclude={exclude}&units={units}&appid={api_key}"
    )
    response = requests.get(complete_url)
    if response.status_code == 200:
        data = response.json()
        current_temperature = round(data["main"]["temp"])
        icon_code = data["weather"][0]["icon"]
        icon_emoji = icon_mapping.get(icon_code, "❓")

        return f"{icon_emoji} {current_temperature}°F"

    else:
        return "Error fetching weather data"


def main():
    parser = argparse.ArgumentParser(description="Get the current weather")
    parser.add_argument("city", type=str, help="City name")
    parser.add_argument("country", type=str, help="Country code")
    args = parser.parse_args()

    location = f"{args.city},{args.country}"

    print(get_weather(location))


if __name__ == "__main__":
    main()
