# Atuin Configuration
# Organized into logical sections with clear, concise settings

# Core Settings
[core]
dialect = "us"
timezone = "local"
style = "auto"
inline_height = 10
invert = false
enter_accept = true

# User Interface
[ui]
keymap_mode = "vim-insert"
keymap_cursor = { emacs = "blink-block", vim_insert = "blink-bar", vim_normal = "steady-block" }

# History and Search Behavior
[history]
filter_mode = "global"
search_mode = "fuzzy"
max_preview_height = 4

# Security and Privacy
[security]
secrets_filter = true
history_filter = [
    # Add your specific regex patterns to exclude sensitive commands
    # "^secret-cmd",
    # "^innocuous-cmd .*--secret=.+"
]

# Sync and Backup
[sync]
records = true
auto_sync = true
sync_frequency = "10m"
sync_address = "https://atuin.gerbil-matrix.ts.net"

# Statistics Tracking
[stats]
common_subcommands = [
    "git", "docker", "kubectl",
    "npm", "yarn", "nix"
]
ignored_commands = [
    "cd", "ls", "pwd"
]

# Dotfiles Management
[dotfiles]
enabled = true
