# version: 1.0.0

add_newline = true
continuation_prompt = "[▸▹ ](dimmed white)"

format = """($os$nix_shell$container$fill$cmd_duration\n)\
$shell\
$env_var\
$jobs\
$sudo\
$username\
$character"""

right_format = """
$kubernetes\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$docker_context\
$package\
$haskell\
$julia\
$lua\
$nodejs\
$perl\
$php\
$python\
$quarto\
$rlang\
$rust\
$swift\
$terraform\
$zig\
$buf\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$custom\
$status\
$battery"""

[fill]
symbol = ' '

[character]
format = "$symbol "
success_symbol = "[❯](blue)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[env_var.VIMSHELL]
format = "[$env_value]($style)"
style = 'green italic'

[sudo]
format = "[$symbol]($style)"
style = "bold italic bright-purple"
symbol = "⋈┈"
disabled = false

[username]
style_user = "bright-yellow bold italic"
style_root = "purple bold italic"
format = "[⭘ $user]($style) "
disabled = false
show_always = false

[directory]
# home_symbol = "⌂"
home_symbol = "~"
truncation_length = 2
truncation_symbol = " "
read_only = " ◈"
use_os_path_sep = true
style = "italic blue"
format = '[$path]($style)[$read_only]($read_only_style)'
repo_root_style = 'bold yellow'
repo_root_format = '[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) [ ](bold bright-red)'

[cmd_duration]
format = "[◄ $duration ](italic white)"

[jobs]
format = "[$symbol$number]($style) "
style = "white"
symbol = "[▶](blue italic)"

[localip]
ssh_only = true
format = " ◯[$localipv4](bold magenta)"
disabled = false

[time]
disabled = false
format = "[ $time]($style)"
time_format = "%R"
utc_time_offset = "local"
style = "italic dimmed white"

[battery]
format = "[ $percentage $symbol]($style)"
full_symbol = "█"
charging_symbol = "[↑](italic bold green)"
discharging_symbol = "↓"
unknown_symbol = "░"
empty_symbol = "▃"

[[battery.display]]
threshold = 20
style = "italic bold red"

[[battery.display]]
threshold = 60
style = "italic dimmed bright-purple"

[[battery.display]]
threshold = 70
style = "italic dimmed yellow"

[git_branch]
format = " [$branch(:$remote_branch)]($style)"
# symbol = " "
symbol = "[](bold italic bright-blue)"
style = "italic bright-red"
truncation_symbol = "⋯"
truncation_length = 11
ignore_branches = ["main", "master"]
only_attached = true

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
style = "cyan"
stashed = ""

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[lua]
format = " [lua](italic) [${symbol}${version}]($style)"
version_format = "${raw}"
symbol = "⨀ "
style = "bold bright-yellow"

[python]
format = " [${symbol}${version}]($style)"
symbol = "[](bold bright-blue)⌊ "
version_format = "${raw}"
style = "bold bright-yellow"

[package]
format = " [pkg](italic dimmed) [$symbol$version ]($style)"
version_format = "${raw}"
symbol = "◨ "
style = "dimmed yellow italic bold"

[docker_context]
symbol = "◧ "
format = " docker [$symbol$context]($style)"

[julia]
symbol = "◎ "
format = " jl [$symbol($version )]($style)"

[memory_usage]
symbol = "▪▫▪ "
format = " mem [${ram}( ${swap})]($style)"

[nix_shell]
style = 'bold italic dimmed blue'
symbol = " "
format = '[$symbol⎪$state⎪]($style)'
impure_msg = '[⌽](bold dimmed red)'
pure_msg = '[⌾](bold dimmed green)'
unknown_msg = '[◌](bold dimmed ellow)'

[os]
disabled = false
style = "bright-white"

[os.symbols]
Macos = " "
Linux = " "
Ubuntu = "󰕈 "
Alpine = " "

[rlang]
symbol = " "

[quarto]
format = "[$symbol $version]($style) "

