GOOSE_PROVIDER: openrouter
extensions:
  developer:
    bundled: true
    display_name: Developer
    enabled: true
    name: developer
    timeout: 300
    type: builtin
GOOSE_MODEL: qwen/qwen3-coder
