version: '1.0'
canvas:
  name: Wake Forest University
  url: https://wakeforest.instructure.com
api:
  rate_limit: 10
  timeout: 30
  retries: 3
  page_size: 100
cache:
  enabled: true
  ttl: 300
  max_size: 1000
logging:
  level: INFO
  format: human
