import = [
  "~/.config/alacritty/themes/themes/tomorrow_night_bright.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 15
padding.y = 15
dynamic_title = true
decorations = "Buttonless"

[font]
size = 13.0
normal.family = "MesloLGL Nerd Font Mono"
normal.style = "Regular"
italic.family = "MesloLGL Nerd Font Mono"
italic.style = "Italic"

[cursor]
style = "Beam"

[scrolling]
history = 20000

[selection]
save_to_clipboard = true

