theme = "gruvbox"

[editor]
line-number = "relative"
cursorline = true
color-modes = true
popup-border = "all"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
git-ignore = true

[editor.indent-guides]
render = true
character = "╎"
skip-levels = 1

[editor.lsp]
enable = true

[editor.soft-wrap]
enable = true

[editor.statusline]
mode.normal = "N"
mode.insert = "I"
mode.select = "S"

[keys.insert.j]
j = "normal_mode"

[keys.normal]
C-s = ":w"
C-c = ":pipe-to ghostty send-keys Enter"
