[[language]]
name = "markdown"
file-types = ["md", "qmd"]
language-servers = [ "marksman" ]

[[language]]
name = "lua"
file-types = [ "lua" ]
language-servers = [ "lua-language-server"]

[[language]]
name = "r"
file-types = [ "r", "R" ]
language-servers = [ "R" ]
